/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/teacher/child-profile`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/daily-report-form`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/all-reports`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/announcements`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/child-manage`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/child-page`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/events`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/forgot_password`; params?: Router.UnknownInputParams; } | { pathname: `/teacher`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/signin`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/teacher-profile`; params?: Router.UnknownInputParams; } | { pathname: `/teacher${'/(tabs)'}/child-reports` | `/teacher/child-reports`; params?: Router.UnknownInputParams; } | { pathname: `/teacher${'/(tabs)'}/profiles` | `/teacher/profiles`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/teacher/child-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/daily-report-form`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/all-reports`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/announcements`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/appointments`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/child-manage`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/child-page`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/events`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/forgot_password`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher/teacher-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher${'/(tabs)'}/child-reports` | `/teacher/child-reports`; params?: Router.UnknownOutputParams; } | { pathname: `/teacher${'/(tabs)'}/profiles` | `/teacher/profiles`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/teacher/child-profile${`?${string}` | `#${string}` | ''}` | `/teacher/daily-report-form${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/teacher/all-reports${`?${string}` | `#${string}` | ''}` | `/teacher/announcements${`?${string}` | `#${string}` | ''}` | `/teacher/appointments${`?${string}` | `#${string}` | ''}` | `/teacher/child-manage${`?${string}` | `#${string}` | ''}` | `/teacher/child-page${`?${string}` | `#${string}` | ''}` | `/teacher/events${`?${string}` | `#${string}` | ''}` | `/teacher/forgot_password${`?${string}` | `#${string}` | ''}` | `/teacher${`?${string}` | `#${string}` | ''}` | `/teacher/signin${`?${string}` | `#${string}` | ''}` | `/teacher/teacher-profile${`?${string}` | `#${string}` | ''}` | `/teacher${'/(tabs)'}/child-reports${`?${string}` | `#${string}` | ''}` | `/teacher/child-reports${`?${string}` | `#${string}` | ''}` | `/teacher${'/(tabs)'}/profiles${`?${string}` | `#${string}` | ''}` | `/teacher/profiles${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/teacher/child-profile`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/daily-report-form`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/all-reports`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/announcements`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/child-manage`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/child-page`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/events`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/forgot_password`; params?: Router.UnknownInputParams; } | { pathname: `/teacher`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/signin`; params?: Router.UnknownInputParams; } | { pathname: `/teacher/teacher-profile`; params?: Router.UnknownInputParams; } | { pathname: `/teacher${'/(tabs)'}/child-reports` | `/teacher/child-reports`; params?: Router.UnknownInputParams; } | { pathname: `/teacher${'/(tabs)'}/profiles` | `/teacher/profiles`; params?: Router.UnknownInputParams; };
    }
  }
}
